[project]
name = "tifeatures"
description = "Simple and Fast Geospatial Features API for PostGIS."
readme = "README.md"
requires-python = ">=3.8"
license = {file = "LICENSE"}
authors = [
    {name = "Vincent Sarago", email = "vincent@developmentseed.com"},
]
keywords = ["FastAPI", "POSTGIS", "OGC Features"]
classifiers = [
    "Intended Audience :: Information Technology",
    "Intended Audience :: Science/Research",
    "License :: OSI Approved :: BSD License",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Topic :: Scientific/Engineering :: GIS",
]
dynamic = ["version"]
dependencies = [
    "asyncpg>=0.23.0",
    "buildpg>=0.3",
    "fastapi>=0.87",
    "jinja2>=2.11.2,<4.0.0",
    "geojson-pydantic>=0.4.3",
    "pygeofilter>=0.2.0,<0.3.0",
    "ciso8601~=2.2.0",
    "starlette-cramjam>=0.3,<0.4",
    "importlib_resources>=1.1.0; python_version < '3.9'",
    "typing_extensions; python_version < '3.9.2'",
]

[project.optional-dependencies]
all = [
    "orjson"
]
test = [
    "pytest",
    "pytest-cov",
    "pytest-asyncio",
    "pytest-benchmark",
    "httpx",
    "psycopg2",
    "pytest-pgsql",
]
dev = [
    "pre-commit",
]
server = [
    "uvicorn[standard]>=0.12.0,<0.16.0",
]
docs = [
    "mkdocs",
    "mkdocs-material",
    "pygments",
    "pdocs",
]

[project.urls]
Source = "https://github.com/developmentseed/tifeatures"
Documentation = "https://developmentseed.org/tifeatures/"

[build-system]
requires = ["flit>=3.2,<4"]
build-backend = "flit_core.buildapi"

[tool.flit.module]
name = "tifeatures"

[tool.flit.sdist]
exclude = [
    "tests/",
    "docs/",
    ".github/",
    "CHANGES.md",
    "CONTRIBUTING.md",
    "dockerfiles",
    "demo",
    ".env*",
    "data/",
    "docker-compose.yml",
]

[tool.isort]
profile = "black"
known_first_party = ["tifeatures"]
known_third_party = ["geojson_pydantic"]
forced_separate = [
    "fastapi",
    "starlette",
]
default_section = "THIRDPARTY"

[tool.mypy]
no_strict_optional = "True"

[tool.pydocstyle]
select = "D1"
match = "(?!test).*.py"
